version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/restaurant_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - db
      - redis
    networks:
      - restaurant-network

  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=restaurant_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - restaurant-network

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    networks:
      - restaurant-network

volumes:
  postgres-data:
  redis-data:

networks:
  restaurant-network:
    driver: bridge