-- V001__INIT.sql

-- Create the customers table if it does not exist
CREATE TABLE IF NOT EXISTS customers (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

-- Insert sample data
INSERT INTO customers (name) VALUES ('John');
INSERT INTO customers (name) VALUES ('Jane');
INSERT INTO customers (name) VALUES ('Alice');
